### ISSUE TITLE
Penultimate CLIP layer

### ISSUE THREAD

**Issue by catboxanon** [p1atdev/LECO#11]
AFAIK, Waifu Diffusion is trained using the penultimate CLIP layer, just as NovelAI did. Currently there isn't a config option for that. Shouldn't there be one? I would imagine that would improve the results for the WD1.5 examples.

**Comment by p1atdev** [comment]
Hi,

SDv2.x models always use the penultimate layer, so it is no problem for SDv2.x like WD1.5. (see https://github.com/huggingface/diffusers/issues/1721#issuecomment-1372737379)

But some v1.x models prefer CLIP skip 2, so I'll add an option for it.

Thanks for pointing out.
