### ISSUE TITLE
[SDXL test]IndexError: tuple index out of range

### ISSUE THREAD

**Issue by sdbds** [p1atdev/LECO#15]
![image](https://github.com/p1atdev/LECO/assets/8085926/063668e5-047f-4f01-9465-924fba9f5937)

**Comment by p1atdev** [comment]
It's maybe fixed. Please try it out on the `sdxl` branch.

**Comment by sdbds** [comment]
> It's maybe fixed. Please try it out on the `sdxl` branch.

thank u for replying！it fixed but there is another error

![image](https://github.com/p1atdev/LECO/assets/8085926/585dd128-8c3c-40d8-ac7a-666d5d8b0e51)

**Comment by p1atdev** [comment]
I fixed it at 4b19877cadf058825163576c7d6c0cf9bd8a8ffd.  (Sorry for the inconvenience because I don't have enough GPU resources for testing...)

**Comment by sdbds** [comment]
> I fixed it at [4b19877](https://github.com/p1atdev/LECO/commit/4b19877cadf058825163576c7d6c0cf9bd8a8ffd). (Sorry for the inconvenience because I don't have enough GPU resources for testing...)

i can make a pr with Paged optimizer which can save 75% VRAM if you need.
it needs gradit checkpoint and bitsandbytes over 0.39.1.

**Comment by sdbds** [comment]
> I fixed it at [4b19877](https://github.com/p1atdev/LECO/commit/4b19877cadf058825163576c7d6c0cf9bd8a8ffd). (Sorry for the inconvenience because I don't have enough GPU resources for testing...)

OK,it works well now.
only it suddenly uses bigger VRAM in dyn res...
i had to use batch size 4 for almost 40G VRAM.

i think maybe dyn res is not use resulation for middle squre.
for example
resulation: 1024
it still use 512X576 to finetune

**Comment by sdbds** [comment]
![image](https://github.com/p1atdev/LECO/assets/8085926/029725a9-1aa2-4bdd-b060-2cc45a218e4d)
SDXL result is nothing changed....
SD 1.5 with same prompt works well

**Comment by p1atdev** [comment]
In previous test (https://huggingface.co/p1atdev/leco/blob/main/elon_musk_sdxl_09.safetensors), it only worked when applied at very high weight (such as 10.0). Please try higher weight if you haven't tried.

I don't know if it will work, but anyway it seems that its effect is less on SDXL than on SDv1.x or SDv2.x. (https://twitter.com/gcem156/status/1682020714579365891)

**Comment by sdbds** [comment]
> In previous test (https://huggingface.co/p1atdev/leco/blob/main/elon_musk_sdxl_09.safetensors), it only worked when applied at very high weight (such as 10.0). Please try higher weight if you haven't tried.
> 
> I don't know if it will work, but anyway it seems that its effect is less on SDXL than on SDv1.x or SDv2.x. (https://twitter.com/gcem156/status/1682020714579365891)

i use weight 10 in comfyui(in comfy_ui,it max weight is 10) but it changed a little alsmot cant see
Should i use higher ```guidance_scale```?

i will test for more result.
