### ISSUE TITLE
unconditional and neutral

### ISSUE THREAD

**Issue by PotatoBananaApple** [p1atdev/LECO#23]
Hey,

Would it be possible to have example how would one use unconditional and neutral?

`word to take the difference from the positive concept`

`starting point for conditioning the target`

These don't really open it for me sadly. 😥

**Comment by sdbds** [comment]
target = trigger words you will use such as lora

positive = postive prompt
unconditional =negativae prompt

train images = (positive - unconditional)* cfg + neutral

example:
i want to make a anime girl image to replace 1girl
positive prompt :1girl, (masterpiece:1.2) 
negative prompt : (3d:1.2)

so
target =1girl
positive = masterpiece
negative = real
neutral = 1girl
CFG = 1.2

**Comment by PotatoBananaApple** [comment]
Thank you for answer.

I was reading the projects linked in reference. In the concept mod  there was mention about the unconditional and it read like this 

`Write to Unconditional: To write a concept to the unconditional model, use the "=" operator after the concept. Example: "alpaca=" causes the system to treat "alpaca" as a default concept or a concept that should always be considered during content generation. -https://github.com/ntc-ai/conceptmod`

But what you said makes more sense to the `word to take the difference from the positive concept`
